name: zomatoo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  lottie: ^3.0.0
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
    - assets/banners/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/zomato_logo.png
  min_sdk_android: 21
